version: '3.7'
services:

  front-react:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    stdin_open: true
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"

  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "9632:9632"
    depends_on:
      - db-dev
    volumes:
      - ./var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules

  db-dev:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=CrysisWarhead020304050
      - POSTGRES_USER=crysis020304050
      - POSTGRES_DB=without_mongo
    ports:
      - "5432:5432"

volumes:
  server-dev:
